spring.application.name=AcademicERP

# Setup MySQL connection
spring.datasource.url=jdbc:mysql://2qko6nSP2ynS8kK.root:PF0KFiVpyjXdXCjc@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/university_db?sslMode=VERIFY_IDENTITY
spring.datasource.username=root
spring.datasource.password=PF0KFiVpyjXdXCjc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Keep default JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false